# Generated by Django 4.1.7 on 2023-02-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_guardinan',
            new_name='parent_guardian',
        ),
    ]
