# Generated by Django 4.1.7 on 2023-02-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_parent_guardinan_student_parent_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bloodgrp',
        ),
    ]
